<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SocietyDetail extends Model
{
    use SoftDeletes;
    public $table = 'society_details';

    public $fillable = [
        'name',
        'abbrevation',
        'domain',
        'default_letter_head',
        'country_id',
        'state_id',
        'logo_path',
        'certificate',
        'pan_number',
        'gst_number',
        'default_holiday_list',
        'create_chart_of_accounts_based_on',
        'default_terms',
        'chart_of_accounts_template',
        'default_currency',
        'default_payable_account_id',
        'default_cash_account_id',
        'default_cost_of_goods_sold_account_id',
        'default_receivable_account_id',
        'default_income_account_id',
        'round_off_account_id',
        'default_payroll_payable_account_id',
        'write_off_account_id',
        'round_off_cost_center_id',
        'exchange_gain_loss_account_id',
        'default_bank_account_id',
        'default_stock_in_hand',
        'accumulated_depreciation_account_id',
        'gain_loss_account_on_asset_disposal_id',
        'depreciation_expense_account_id',
        'asset_depreciation_cost_center_id',
        'default_employee_advance_id',
        'salary_advance_id',
        'default_bank_group_id',
        'default_bank_ledger_id',
        'default_tax_group_id',
        'default_tax_ledger_id',
        'default_ledger_setapart_id',
        'default_cgst_input_ledger_id',
        'default_sgst_input_ledger_id',
        'default_igst_input_ledger_id',
        'default_cgst_output_ledger_id',
        'default_sgst_output_ledger_id',
        'default_igst_output_ledger_id',
        'default_mismatch_income_id',
        'default_mismatch_expense_id',
        'round_off_id',
        'supplier_advance_ledger_id',
        'customer_advance_ledger_id',
        'tcs_ledger_id',
        'tds_ledger_id',
        'phone_no',
        'email',
        'website',
        'address',
        'employee_ids',
        'default_other_charges_id',
        'default_transport_charges_id',
        'default_bouns_id',
        'default_cash_debit_ledger_id',
        'default_cash_credit_ledger_id',
        'default_bank_charges_ledger_id',
        'default_purchase_group_id',
        'default_sales_group_id',
        'temporary_ledger_id',
        'retention_amount_ledger_id',
        'salary_payable_ledger_id',
        'certificate_path',
        'created_by',
        'updated_by'
    ];

    public static array $rules = [
        'name' => 'required',
        'abbrevation',
        'domain',
        'default_letter_head',
        'country_id',
        'state_id',
        'logo_path',
        'certificate',
        'pan_number' => 'required',
        'gst_number' => 'required',
        'default_holiday_list',
        'create_chart_of_accounts_based_on',
        'default_terms',
        'chart_of_accounts_template',
        'default_currency',
        'default_payable_account_id',
        'default_cash_account_id',
        'default_cost_of_goods_sold_account_id',
        'default_receivable_account_id',
        'default_income_account_id',
        'round_off_account_id',
        'default_payroll_payable_account_id',
        'write_off_account_id',
        'round_off_cost_center_id',
        'exchange_gain_loss_account_id',
        'default_bank_account_id',
        'default_stock_in_hand',
        'accumulated_depreciation_account_id',
        'gain_loss_account_on_asset_disposal_id',
        'depreciation_expense_account_id',
        'asset_depreciation_cost_center_id',
        'default_employee_advance_id',
        'salary_advance_id',
        'default_bank_group_id',
        'default_bank_ledger_id',
        'default_tax_group_id',
        'default_tax_ledger_id',
        'default_ledger_setapart_id',
        'default_cgst_input_ledger_id',
        'default_sgst_input_ledger_id',
        'default_igst_input_ledger_id',
        'default_cgst_output_ledger_id',
        'default_sgst_output_ledger_id',
        'default_igst_output_ledger_id',
        'default_mismatch_income_id',
        'default_mismatch_expense_id',
        'round_off_id',
        'supplier_advance_ledger_id',
        'customer_advance_ledger_id',
        'tcs_ledger_id',
        'tds_ledger_id',
        'phone_no',
        'email',
        'website',
        'address',
        'employee_ids',
        'default_other_charges_id',
        'default_transport_charges_id',
        'default_bouns_id',
        'default_cash_debit_ledger_id',
        'default_cash_credit_ledger_id',
        'default_bank_charges_ledger_id',
        'default_purchase_group_id',
        'default_sales_group_id',
        'temporary_ledger_id',
        'retention_amount_ledger_id',
        'salary_payable_ledger_id',
        'certificate_path',
        'created_by',
        'updated_by'
    ];
}
